#include "puzzles/color_match_puzzle.h"

#include <algorithm>
#include <cmath>

#include "raylib.h"

namespace {

constexpr int palette_count = ColorMatchPuzzle::palette_count;
constexpr int column_count = ColorMatchPuzzle::column_count;
constexpr int stage_count = ColorMatchPuzzle::stage_count;
constexpr int disc_sectors = ColorMatchPuzzle::disc_sectors;
constexpr int disc_rings = ColorMatchPuzzle::disc_rings;

// --- layout -----------------------------------------------------------------
constexpr float disc_cx = 182.0f;
constexpr float disc_cy = 300.0f;
constexpr float disc_radius = 148.0f;

constexpr float panel_x = 350.0f;
constexpr float panel_w = 134.0f;
constexpr float preview_y = 188.0f;
constexpr float preview_h = 134.0f;
constexpr float preview_inset = 12.0f;

constexpr Vector2 lamp_pos{module_tex_size - 54.0f, 48.0f};

Rectangle preview_ground() {
    return Rectangle{panel_x, preview_y, panel_w, preview_h};
}

Rectangle preview_swatch() {
    return Rectangle{panel_x + preview_inset, preview_y + preview_inset,
                     panel_w - 2.0f * preview_inset,
                     preview_h - 2.0f * preview_inset};
}

Rectangle submit_rect() {
    return Rectangle{panel_x, 376.0f, panel_w, 66.0f};
}

// --- the wheel --------------------------------------------------------------
// Angle is Oklab hue, radius runs from a neutral grey at the centre out to the
// hue's strongest colour: the gamut cusp's lightness, with chroma capped so the
// rim is rich rather than fluorescent. Lightness therefore varies with hue,
// which is what a saturated palette needs -- a vivid yellow is light, a vivid
// blue is dark -- and is also what keeps the colours apart for a colour-blind
// player, who separates them largely by lightness.
constexpr float neutral_lightness = 0.62f;
constexpr float chroma_cap = 0.20f;
constexpr float cusp_step_degrees = 2.0f;

struct Cusp {
    float lightness;
    float chroma;
};

// The most chromatic in-gamut colour at each hue, every cusp_step_degrees.
// Generated by `python3 scripts/color_palette.py cusp`; the same table and the
// same interpolation run in the script, so the wheel the module draws and the
// patches the manual prints cannot drift apart.
constexpr int cusp_count = 180;
constexpr Cusp cusp_table[cusp_count] = {
    {0.6500f, 0.2601f}, {0.6400f, 0.2585f}, {0.6400f, 0.2576f},
    {0.6400f, 0.2569f}, {0.6400f, 0.2564f}, {0.6400f, 0.2547f},
    {0.6400f, 0.2525f}, {0.6300f, 0.2519f}, {0.6300f, 0.2521f},
    {0.6300f, 0.2525f}, {0.6300f, 0.2531f}, {0.6300f, 0.2539f},
    {0.6300f, 0.2549f}, {0.6300f, 0.2553f}, {0.6300f, 0.2555f},
    {0.6300f, 0.2528f}, {0.6400f, 0.2427f}, {0.6500f, 0.2339f},
    {0.6600f, 0.2262f}, {0.6700f, 0.2194f}, {0.6800f, 0.2135f},
    {0.6900f, 0.2078f}, {0.7000f, 0.2011f}, {0.7000f, 0.1969f},
    {0.7100f, 0.1934f}, {0.7200f, 0.1904f}, {0.7300f, 0.1859f},
    {0.7300f, 0.1830f}, {0.7400f, 0.1812f}, {0.7500f, 0.1791f},
    {0.7500f, 0.1759f}, {0.7600f, 0.1750f}, {0.7700f, 0.1742f},
    {0.7700f, 0.1715f}, {0.7800f, 0.1712f}, {0.7900f, 0.1712f},
    {0.7900f, 0.1692f}, {0.8000f, 0.1696f}, {0.8100f, 0.1702f},
    {0.8100f, 0.1689f}, {0.8200f, 0.1699f}, {0.8300f, 0.1711f},
    {0.8400f, 0.1725f}, {0.8400f, 0.1720f}, {0.8500f, 0.1738f},
    {0.8600f, 0.1758f}, {0.8700f, 0.1780f}, {0.8800f, 0.1804f},
    {0.8900f, 0.1829f}, {0.9000f, 0.1848f}, {0.9100f, 0.1879f},
    {0.9200f, 0.1926f}, {0.9300f, 0.1964f}, {0.9400f, 0.2005f},
    {0.9500f, 0.2049f}, {0.9600f, 0.2096f}, {0.9600f, 0.2125f},
    {0.9500f, 0.2136f}, {0.9500f, 0.2172f}, {0.9400f, 0.2188f},
    {0.9400f, 0.2209f}, {0.9300f, 0.2256f}, {0.9200f, 0.2284f},
    {0.9200f, 0.2342f}, {0.9100f, 0.2380f}, {0.9100f, 0.2448f},
    {0.9000f, 0.2499f}, {0.8900f, 0.2555f}, {0.8900f, 0.2647f},
    {0.8800f, 0.2720f}, {0.8700f, 0.2801f}, {0.8600f, 0.2894f},
    {0.8600f, 0.2789f}, {0.8700f, 0.2659f}, {0.8700f, 0.2518f},
    {0.8700f, 0.2396f}, {0.8700f, 0.2289f}, {0.8700f, 0.2194f},
    {0.8800f, 0.2115f}, {0.8800f, 0.2059f}, {0.8800f, 0.1991f},
    {0.8800f, 0.1930f}, {0.8800f, 0.1876f}, {0.8800f, 0.1826f},
    {0.8800f, 0.1782f}, {0.8900f, 0.1751f}, {0.8900f, 0.1726f},
    {0.8900f, 0.1693f}, {0.8900f, 0.1664f}, {0.8900f, 0.1638f},
    {0.8900f, 0.1615f}, {0.8900f, 0.1595f}, {0.8900f, 0.1577f},
    {0.9000f, 0.1574f}, {0.9000f, 0.1565f}, {0.9000f, 0.1554f},
    {0.9000f, 0.1545f}, {0.9000f, 0.1539f}, {0.9000f, 0.1530f},
    {0.8900f, 0.1514f}, {0.8800f, 0.1496f}, {0.8700f, 0.1480f},
    {0.8600f, 0.1467f}, {0.8500f, 0.1454f}, {0.8500f, 0.1453f},
    {0.8400f, 0.1453f}, {0.8300f, 0.1446f}, {0.8200f, 0.1442f},
    {0.8100f, 0.1439f}, {0.8100f, 0.1456f}, {0.8000f, 0.1457f},
    {0.7900f, 0.1460f}, {0.7800f, 0.1465f}, {0.7800f, 0.1479f},
    {0.7700f, 0.1502f}, {0.7600f, 0.1515f}, {0.7500f, 0.1530f},
    {0.7400f, 0.1549f}, {0.7300f, 0.1571f}, {0.7200f, 0.1597f},
    {0.7100f, 0.1627f}, {0.7100f, 0.1662f}, {0.6900f, 0.1702f},
    {0.6800f, 0.1749f}, {0.6700f, 0.1804f}, {0.6600f, 0.1869f},
    {0.6500f, 0.1924f}, {0.6300f, 0.2007f}, {0.6100f, 0.2084f},
    {0.6000f, 0.2191f}, {0.5700f, 0.2327f}, {0.5400f, 0.2501f},
    {0.4900f, 0.2854f}, {0.4600f, 0.3075f}, {0.4600f, 0.3071f},
    {0.4600f, 0.3016f}, {0.4700f, 0.3021f}, {0.4700f, 0.2979f},
    {0.4800f, 0.2980f}, {0.4800f, 0.2949f}, {0.4900f, 0.2953f},
    {0.4900f, 0.2924f}, {0.5000f, 0.2941f}, {0.5100f, 0.2904f},
    {0.5100f, 0.2924f}, {0.5200f, 0.2913f}, {0.5200f, 0.2908f},
    {0.5300f, 0.2929f}, {0.5400f, 0.2917f}, {0.5400f, 0.2916f},
    {0.5500f, 0.2937f}, {0.5600f, 0.2957f}, {0.5700f, 0.2953f},
    {0.5800f, 0.2953f}, {0.5800f, 0.2966f}, {0.5900f, 0.2985f},
    {0.6000f, 0.3004f}, {0.6100f, 0.3022f}, {0.6200f, 0.3039f},
    {0.6300f, 0.3056f}, {0.6500f, 0.3087f}, {0.6600f, 0.3132f},
    {0.6700f, 0.3150f}, {0.6800f, 0.3164f}, {0.7000f, 0.3209f},
    {0.6900f, 0.3146f}, {0.6900f, 0.3115f}, {0.6900f, 0.3040f},
    {0.6800f, 0.3010f}, {0.6800f, 0.2965f}, {0.6700f, 0.2912f},
    {0.6700f, 0.2886f}, {0.6700f, 0.2831f}, {0.6600f, 0.2796f},
    {0.6600f, 0.2775f}, {0.6600f, 0.2742f}, {0.6500f, 0.2694f},
    {0.6500f, 0.2677f}, {0.6500f, 0.2662f}, {0.6500f, 0.2644f},
};

// --- the palette ------------------------------------------------------------
// Generated and checked by scripts/color_palette.py. hue and radius are the
// point's place on the wheel; ink is what that point draws in sRGB, cached here
// so the manual's patches can be compared against this table without the parser
// doing a colour conversion.
struct Swatch {
    float hue;
    float radius;
    Color ink;
};

constexpr Swatch palette[palette_count] = {
    {   7.950f, 1.0000f, Color{233,  71, 117, 255}},  // #E94775
    {  30.620f, 1.0000f, Color{234,  74,  53, 255}},  // #EA4A35
    {  56.660f, 0.9851f, Color{253, 136,  12, 255}},  // #FD880C
    {  62.200f, 0.5176f, Color{197, 144,  96, 255}},  // #C59060
    {  87.370f, 0.9991f, Color{252, 196,   0, 255}},  // #FCC400
    { 107.880f, 0.6027f, Color{203, 201, 104, 255}},  // #CBC968
    { 111.620f, 1.0000f, Color{247, 254,  54, 255}},  // #F7FE36
    { 145.240f, 0.5500f, Color{130, 194, 132, 255}},  // #82C284
    { 153.450f, 0.9638f, Color{ 77, 245, 147, 255}},  // #4DF593
    { 171.470f, 0.7518f, Color{ 89, 224, 187, 255}},  // #59E0BB
    { 196.720f, 1.0000f, Color{  3, 251, 255, 255}},  // #03FBFF
    { 225.010f, 1.0000f, Color{  5, 202, 254, 255}},  // #05CAFE
    { 247.250f, 0.6663f, Color{ 79, 151, 213, 255}},  // #4F97D5
    { 266.720f, 1.0000f, Color{ 38,  70, 197, 255}},  // #2646C5
    { 292.300f, 0.6512f, Color{118,  98, 184, 255}},  // #7662B8
    { 349.210f, 0.5550f, Color{191, 112, 151, 255}},  // #BF7097
};

// The key word the module prints. Colour-neutral -- a word that suggests a hue
// would hand the Expert the answer without the manual -- and no two share an
// initial letter, which is what a mishearing turns on.
constexpr const char* key_words[palette_count] = {
    "ANVIL", "BUREAU", "CIPHER", "DELTA", "ENVOY", "FULCRUM",
    "GAZEBO", "HAVEN", "INDEX", "JIGSAW", "KESTREL", "LEDGER",
    "MASON", "NOMAD", "ORBIT", "PLINTH",
};

// Which colour a key names depends on the battery count, so the Defuser has to
// read a widget out before the Expert can look anything up. The three columns
// are mutually fixed-point-free: no key keeps its colour across two of them, so
// misreading the bucket is always wrong rather than sometimes harmless.
constexpr int column_map[column_count][palette_count] = {
    { 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15},
    {13,  4,  5,  2, 11,  6, 12,  8,  9, 14,  7, 15,  3,  0,  1, 10},
    {11,  9,  7, 15,  2,  3, 13,  0,  4, 10,  1,  5,  8, 14,  6, 12},
};

// --- colour space -----------------------------------------------------------
// Oklab -> sRGB, the same conversion scripts/color_palette.py runs. Oklab
// rather than CIELAB because the wheel's rim is saturated, and CIELAB's hue
// lines bend badly for saturated blues.
float srgb_encode(float v) {
    if (v <= 0.0031308f) return 12.92f * v;
    return 1.055f * std::pow(v, 1.0f / 2.4f) - 0.055f;
}

void oklab_to_linear(float lightness, float a, float b, float out[3]) {
    const float l_ = lightness + 0.3963377774f * a + 0.2158037573f * b;
    const float m_ = lightness - 0.1055613458f * a - 0.0638541728f * b;
    const float s_ = lightness - 0.0894841775f * a - 1.2914855480f * b;
    const float l = l_ * l_ * l_;
    const float m = m_ * m_ * m_;
    const float s = s_ * s_ * s_;
    out[0] = 4.0767416621f * l - 3.3077115913f * m + 0.2309699292f * s;
    out[1] = -1.2684380046f * l + 2.6097574011f * m - 0.3413193965f * s;
    out[2] = -0.0041960863f * l - 0.7034186147f * m + 1.7076147010f * s;
}

void oklch_to_linear(float lightness, float chroma, float hue, float out[3]) {
    const float rad = hue * DEG2RAD;
    oklab_to_linear(lightness, chroma * std::cos(rad), chroma * std::sin(rad),
                    out);
}

bool linear_in_gamut(const float lin[3]) {
    for (int i = 0; i < 3; ++i) {
        if (lin[i] < -1.0e-4f || lin[i] > 1.0f + 1.0e-4f) return false;
    }
    return true;
}

// Largest in-gamut chroma at a lightness and hue, by bisection -- the same
// thirty steps the script takes, so the two land on the same colour.
float max_chroma(float lightness, float hue) {
    float lo = 0.0f;
    float hi = 0.45f;
    float lin[3];
    for (int i = 0; i < 30; ++i) {
        const float mid = 0.5f * (lo + hi);
        oklch_to_linear(lightness, mid, hue, lin);
        if (linear_in_gamut(lin)) {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    return lo;
}

Cusp cusp_at(float hue) {
    hue = std::fmod(hue, 360.0f);
    if (hue < 0.0f) hue += 360.0f;
    const float pos = hue / cusp_step_degrees;
    const int lo = static_cast<int>(pos) % cusp_count;
    const int hi = (lo + 1) % cusp_count;
    const float f = pos - static_cast<float>(static_cast<int>(pos));
    const Cusp& a = cusp_table[lo];
    const Cusp& b = cusp_table[hi];
    return Cusp{a.lightness + (b.lightness - a.lightness) * f,
                a.chroma + (b.chroma - a.chroma) * f};
}

// A point on the wheel, as an sRGB colour. Reducing chroma at a fixed lightness
// never leaves the gamut, but the lightness ramp can overshoot near the cusp,
// so the chroma is clamped to what that lightness can actually hold.
Color wheel_color(float hue, float radius) {
    const Cusp cusp = cusp_at(hue);
    const float lightness =
            neutral_lightness + (cusp.lightness - neutral_lightness) * radius;
    const float chroma =
            std::min(radius * std::min(cusp.chroma, chroma_cap),
                     max_chroma(lightness, hue));

    float lin[3];
    oklch_to_linear(lightness, chroma, hue, lin);
    unsigned char out[3];
    for (int i = 0; i < 3; ++i) {
        const float clamped = std::min(1.0f, std::max(0.0f, lin[i]));
        out[i] = static_cast<unsigned char>(
                srgb_encode(clamped) * 255.0f + 0.5f);
    }
    return Color{out[0], out[1], out[2], 255};
}

// --- disc geometry ----------------------------------------------------------
// Screen angle, not hue: raylib's y grows downward, so a point drawn at angle
// phi carries the colour of hue -phi. Working in phi keeps the drawing and the
// hit test on one formula instead of two that have to agree.
float ring_radius(int ring) {
    return (static_cast<float>(ring) + 0.5f) / static_cast<float>(disc_rings);
}

float sector_angle(int sector) {
    return 360.0f * (static_cast<float>(sector) + 0.5f) /
           static_cast<float>(disc_sectors);
}

void draw_centered(const char* text, Rectangle box, int size, Color color) {
    DrawText(text,
             static_cast<int>(box.x + (box.width - MeasureText(text, size)) *
                                              0.5f),
             static_cast<int>(box.y + (box.height - size) * 0.5f), size, color);
}

}  // namespace

void ColorMatchPuzzle::init(const BombAttributes& attrs, std::mt19937& rng) {
    column_ = attrs.battery_count <= 1 ? 0
                                       : (attrs.battery_count <= 3 ? 1 : 2);

    // The keys are re-dealt after a strike, so the module keeps its own engine
    // rather than holding on to the bomb's.
    key_rng_.seed(rng());
    deal_keys();

    for (int ring = 0; ring < disc_rings; ++ring) {
        const float radius = ring_radius(ring);
        for (int sector = 0; sector < disc_sectors; ++sector) {
            disc_[ring * disc_sectors + sector] =
                    wheel_color(-sector_angle(sector), radius);
        }
    }
}

void ColorMatchPuzzle::deal_keys() {
    std::uniform_int_distribution<int> pick(0, palette_count - 1);
    keys_[0] = pick(key_rng_);
    do {
        keys_[1] = pick(key_rng_);
    } while (keys_[1] == keys_[0]);
}

void ColorMatchPuzzle::disc_coords(Vector2 p, float& x, float& y) const {
    // Unit-disc coordinates, y flipped so the wheel turns the way it is drawn.
    x = (p.x - disc_cx) / disc_radius;
    y = -(p.y - disc_cy) / disc_radius;
    const float len = std::sqrt(x * x + y * y);
    if (len > 1.0f) {
        x /= len;
        y /= len;
    }
}

bool ColorMatchPuzzle::disc_at_pixel(Vector2 p, float& x, float& y) const {
    const float dx = p.x - disc_cx;
    const float dy = p.y - disc_cy;
    // Half a pixel of slack: the rim colours sit at radius exactly 1, and the
    // pixel that draws one can round to a hair outside the circle.
    if (std::sqrt(dx * dx + dy * dy) > disc_radius + 0.5f) return false;
    disc_coords(p, x, y);
    return true;
}

int ColorMatchPuzzle::nearest_swatch(float x, float y) const {
    // Graded on the wheel rather than in colour space: the wheel is what the
    // Defuser aims at, and the palette search is what guarantees every entry a
    // cell wide enough to hit.
    int best = 0;
    float best_dist = -1.0f;
    for (int i = 0; i < palette_count; ++i) {
        const float rad = palette[i].hue * DEG2RAD;
        const float dx = x - palette[i].radius * std::cos(rad);
        const float dy = y - palette[i].radius * std::sin(rad);
        const float away = dx * dx + dy * dy;
        if (best_dist < 0.0f || away < best_dist) {
            best_dist = away;
            best = i;
        }
    }
    return best;
}

void ColorMatchPuzzle::update(const ModuleInput& in, const BombContext& ctx,
                              float dt) {
    (void)ctx;
    (void)dt;
    if (is_solved()) return;

    // The crosshair is placed by pressing and refined by dragging: the pick has
    // to be nudged while the preview is watched, which a discrete tap cannot
    // do. Game::handle_pointer holds pointer_pos at the press pixel once the
    // finger leaves the face, so a drag off the disc simply stops moving it.
    float x = 0.0f;
    float y = 0.0f;
    if (in.pressed && disc_at_pixel(in.pointer_pos, x, y)) dragging_ = true;
    if (dragging_ && in.held) {
        // Once the drag has started the pointer is followed wherever it goes,
        // clamped to the rim, so sliding outwards parks on full strength
        // instead of freezing.
        disc_coords(in.pointer_pos, x, y);
        pick_x_ = x;
        pick_y_ = y;
        has_pick_ = true;
    }
    if (in.released || !in.held) dragging_ = false;

    if (!in.tapped || !has_pick_) return;
    if (!CheckCollisionPointRec(in.tap_pos, submit_rect())) return;

    // Graded by which palette entry the pick lands nearest to, so the Defuser
    // never has to match a colour exactly -- only to land in its cell.
    const int wanted = column_map[column_][keys_[stage_]];
    if (nearest_swatch(pick_x_, pick_y_) == wanted) {
        ++stage_;
        has_pick_ = false;
        if (stage_ >= stage_count) mark_solved();
        return;
    }

    // A wrong colour re-deals both keys. Without that the pair could work the
    // module by elimination instead of by describing anything.
    raise_strike();
    stage_ = 0;
    has_pick_ = false;
    deal_keys();
}

void ColorMatchPuzzle::draw() {
    DrawRectangle(0, 0, module_tex_size, module_tex_size,
                  Color{32, 33, 38, 255});

    // stage_ runs past the last key on the winning pick, so the label has to
    // stop reading the array rather than clamp into it.
    if (is_solved()) {
        DrawText("KEY", 34, 26, 20, Color{60, 63, 70, 255});
        DrawText("DONE", 34, 52, 44, Color{90, 220, 120, 255});
    } else {
        DrawText("KEY", 34, 26, 20, Color{150, 158, 170, 255});
        DrawText(key_words[keys_[stage_]], 34, 52, 44,
                 Color{226, 228, 234, 255});
    }
    for (int i = 0; i < stage_count; ++i) {
        DrawCircle(44 + i * 30, 122, 9,
                   i < stage_ ? Color{90, 220, 120, 255}
                              : Color{60, 63, 70, 255});
    }

    for (int ring = 0; ring < disc_rings; ++ring) {
        const float inner = disc_radius * static_cast<float>(ring) /
                            static_cast<float>(disc_rings);
        const float outer = disc_radius * static_cast<float>(ring + 1) /
                            static_cast<float>(disc_rings);
        for (int sector = 0; sector < disc_sectors; ++sector) {
            const float start = 360.0f * static_cast<float>(sector) /
                                static_cast<float>(disc_sectors);
            const float end = 360.0f * static_cast<float>(sector + 1) /
                              static_cast<float>(disc_sectors);
            DrawRing(Vector2{disc_cx, disc_cy}, inner, outer, start, end, 1,
                     disc_[ring * disc_sectors + sector]);
        }
    }
    DrawCircleLines(static_cast<int>(disc_cx), static_cast<int>(disc_cy),
                    disc_radius + 1.0f, Color{16, 16, 20, 255});
    DrawCircleLines(static_cast<int>(disc_cx), static_cast<int>(disc_cy),
                    disc_radius + 2.0f, Color{16, 16, 20, 255});

    if (has_pick_) {
        const Vector2 at{disc_cx + pick_x_ * disc_radius,
                         disc_cy - pick_y_ * disc_radius};
        // A pale ring between two dark ones: whatever hue sits underneath,
        // one of the two has contrast against it. Drawn as pairs of adjacent
        // radii because raylib's circle outline is a single pixel wide, which
        // disappears once the face is a bay away from the camera.
        const Color dark{16, 16, 20, 255};
        const Color pale{240, 242, 246, 255};
        for (float r = 16.0f; r <= 17.0f; r += 1.0f) {
            DrawCircleLinesV(at, r, dark);
        }
        for (float r = 13.0f; r <= 15.0f; r += 1.0f) {
            DrawCircleLinesV(at, r, pale);
        }
        for (float r = 11.0f; r <= 12.0f; r += 1.0f) {
            DrawCircleLinesV(at, r, dark);
        }
        DrawLineEx(Vector2{at.x - 24.0f, at.y}, Vector2{at.x - 18.0f, at.y},
                   3.0f, pale);
        DrawLineEx(Vector2{at.x + 18.0f, at.y}, Vector2{at.x + 24.0f, at.y},
                   3.0f, pale);
        DrawLineEx(Vector2{at.x, at.y - 24.0f}, Vector2{at.x, at.y - 18.0f},
                   3.0f, pale);
        DrawLineEx(Vector2{at.x, at.y + 18.0f}, Vector2{at.x, at.y + 24.0f},
                   3.0f, pale);
    }

    // The preview sits on a neutral grey rather than the panel's dark plastic:
    // the same colour reads lighter and more saturated against a dark ground,
    // and the manual prints its patches on grey for the same reason.
    DrawText("PICKED", static_cast<int>(panel_x), 164, 20,
             Color{150, 158, 170, 255});
    DrawRectangleRec(preview_ground(), Color{138, 138, 138, 255});
    if (has_pick_) {
        // The wheel's colour at unit coordinates: the hue is the angle those
        // coordinates make, which is how the cells were filled in init().
        const float hue = std::atan2(pick_y_, pick_x_) * RAD2DEG;
        const float radius = std::sqrt(pick_x_ * pick_x_ + pick_y_ * pick_y_);
        DrawRectangleRec(preview_swatch(),
                         wheel_color(hue, std::min(1.0f, radius)));
    } else {
        DrawRectangleRec(preview_swatch(), Color{92, 92, 92, 255});
        draw_centered("--", preview_swatch(), 30, Color{138, 138, 138, 255});
    }
    DrawRectangleLinesEx(preview_ground(), 3, Color{16, 16, 20, 255});

    const Rectangle submit = submit_rect();
    DrawRectangleRec(submit, has_pick_ ? Color{58, 62, 72, 255}
                                       : Color{40, 42, 50, 255});
    DrawRectangleLinesEx(submit, 4, Color{16, 16, 20, 255});
    draw_centered("SUBMIT", submit, 28,
                  has_pick_ ? Color{226, 228, 234, 255}
                            : Color{110, 116, 128, 255});

    DrawCircle(static_cast<int>(lamp_pos.x), static_cast<int>(lamp_pos.y), 19,
               is_solved() ? Color{90, 220, 120, 255}
                           : Color{60, 63, 70, 255});
}
